# Generated by Django 5.2 on 2025-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
